= Surge Protocol

:network-byte-order: footnote:[wikipedia: https://en.wikipedia.org/wiki/Endianness#Networking[Networking Endianness]]

The Surge protocol is based on datagrams, e.g. UDP. It does not handle connections, encryption, counter replay attacks, IP Spoofing, sessions, etc, since they differ widly on different unreliable datagram services and transports.

If not already decided on an existing unreliable datagram transport, netcode.io looks interesting.

All values are sent in Network Byte Order {network-byte-order} (big endian) unless otherwise specified.


== Datagram

=== Snapshot Datagrams

Sent from authoritative host to the client. When connection quality is good, only one snapshot is sent after each tick.
If snapshots are dropped or network quality is likely to be bad, a few extra delta snapshots are sent (redundancy).

Contains all fields that changed for all  ghosts that changed during each of the snapshots.
Also contains fully non compressed correction state for the predicting avatars on the client
 (usually one, unless multiple local players). The ghosts and the predicting avatars should be deterministic in isolation.

[cols="1,2,4"]
|===
|Type|Name|Description

|<<Ordered Datagrams>>
|OrderedDatagrams
|See <<Ordered Datagrams>>

|`+U8+`
|DatagramType
|0x01 = DeltaSnapshots

|`U16`
|PongTimeMsClientLowerBits
|The lower bits of monotonic time last received from the client. Used to calculate Round Trip Time.

|`S8`
|Input Step Id diff
|The input TickId diff. Optimal values are around +1 to +3. Negative values indicates that the host had to guess input values since the input queue was starved.

|`U32`
|LastSnapshotId
|Last snapshotID in the range

|`U8`
|SnapshotCount
|How many snapshots are contained going backwards. Must be at least one.

`FirstSnapshotID = LastSnapshotId - (SnapshotCount - 1)`.

|`U8`
|PayloadPartIndex
|The (0x7F) part of the octet indicates which index of the payload that should be reassembled. +
If the highest bit is set (0x80), then this is the last packet and the payload can be reassembled and put in a queue.

|`U8[]`
|PayloadSlice
|Slice of the complete payload. Between 1 and 1100 octets.

|===


For more info about the `PayloadSlice`, check out xref:snapshot.adoc#SnapshotMessage[Snapshot Message]

=== Predicted Logical Input Datagrams
Sent by client to authoritative host for the locally predicted avatars on the client (usually just one).

The protocol has, by design, no way of splitting in multiple datagrams.

If we have around 300 ms as a maximum latency from a QoS perspective and assume a 16ms simulation tick, that comes down to around 16 locally predicted inputs.

With a redundancy about 16, that must fit in a single datagram, results in a max size of each logical input to 70 octets.

[cols="1,2,4"]
|===
|Type|Name|Description

|`OrderedDatagrams`
|OrderedDatagrams
|See <<Ordered Datagrams>>

|`U8`
|DatagramType
|0x02 = Predicted Inputs

|`<<Snapshot Receive Status>>`
|Snapshot Receive Status
|See <<Snapshot Receive Status>>

|`U16`
|Client Monotonic Ping Time lower bits
|The lower bits of the monotonic time.

|`U8`
|InputStreamCount
|The number of input streams. One stream for each local player. Usually one, unless for example splitscreen.

|`LogicalInputStream [InputStreamCount]`
|InputChunks
|Input chunks repeated `InputStreamCount` times. See <<Logical Input Stream>>.

|===

==== Logical Input Stream

|===
|`U8`
|LocalPlayerIndex
|The local player index.

The local player index is something that the client assigns on its own. Usually from 1-4, which represents the bound input devices in order.

|`U32`
|FirstSnapshotId
|Input was predicted and applied when state was at this `FirstSnapshotId`. Receiver should assume that it increased by one
after each `InputStreamCount` LogicalInputChunks.

|`U8`
|InputCount
|The number of inputs that follows, in the range of 0 to 16.

|`LogicalInputChunk [InputCount]`
|InputChunks
|Input chunks repeated `InputCount` times. See <<Logical Input Chunk>>.

|===

==== Logical Input Chunk

[cols="1,1,4"]
|===
|Type|Name|Description

|`U8`
|PayloadLength
|The number of following octets. 1-70 octets if one stream (with full 16 redundancy), 1-35 for two streams. 0 is allowed if no data available yet, like a recently joined player.

|`U8[PayloadLength]`
|Payload
|Game specific serialized logical input. The logical input can be delta compressed, but only with reference to inputs that are serialized within this datagram.

|===


== Sections

=== Ordered Datagrams

Makes sure that the datagrams are received in order and that duplicates and reordered datagrams are discarded.
Normally this is handled by the transport layer used, but needed when using unsecure UDP and in all cases as an extra sanity check.
Receiver should discard any datagram that is not considered a successor to the previously received datagram.
If no datagram has been received, just accept the first one.

[cols="1,1,4"]
|===
|Type|Name|Description

|`U8`
|Sequence ID
|Increasing every datagram sent. Wraps around to zero after 0xff (255), Starts with zero.
|===


=== Snapshot Receive Status

Sent from Client to Host, to signal the latest useful snapshot that was received and put in a queue. As well as how many that was dropped after that (to the Clients' knowledge). The host will resend any dropped snapshots.

[cols="1,2,4"]
|===
|Type|Name|Description

|`U32`
|TickIdForLastSnapshot
|The TickId for the last Snapshot that the client received in a consecutive unbroken sequence.

|`U8`
|DroppedSnapshotCount
|The number of dropped snapshots after `TickIdForLastSnapshot`. 0 - 30.

|===
